// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA62Risb_LaDt4orGYmMXYdl-RGMYEJBHY',
    appId: '1:88015382345:web:560508ace06ddd54e41c98',
    messagingSenderId: '88015382345',
    projectId: 'my-first-app-11715',
    authDomain: 'my-first-app-11715.firebaseapp.com',
    storageBucket: 'my-first-app-11715.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSzuWRz2fnKOlV3JqJfGTglXSSpzdVH24',
    appId: '1:88015382345:android:666e2496baedcf2be41c98',
    messagingSenderId: '88015382345',
    projectId: 'my-first-app-11715',
    storageBucket: 'my-first-app-11715.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwbgeORyJcmaYaxoGUuHO4qIKlT_TG3m8',
    appId: '1:88015382345:ios:6287448f0e1facece41c98',
    messagingSenderId: '88015382345',
    projectId: 'my-first-app-11715',
    storageBucket: 'my-first-app-11715.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwbgeORyJcmaYaxoGUuHO4qIKlT_TG3m8',
    appId: '1:88015382345:ios:6287448f0e1facece41c98',
    messagingSenderId: '88015382345',
    projectId: 'my-first-app-11715',
    storageBucket: 'my-first-app-11715.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA62Risb_LaDt4orGYmMXYdl-RGMYEJBHY',
    appId: '1:88015382345:web:c719c2898f65f472e41c98',
    messagingSenderId: '88015382345',
    projectId: 'my-first-app-11715',
    authDomain: 'my-first-app-11715.firebaseapp.com',
    storageBucket: 'my-first-app-11715.firebasestorage.app',
  );
}
